### PR TITLE
Advertise the GitHub bugtracker

### PR DESCRIPTION
**Pull request by atoomic**
Advertise the GitHub bug tracker instead of RT

### CODE REVIEW

**Comment by kohts** [comment]
Hey @atoomic, would you like to take over the support of the module? I've been kind of inactive on it and I'd be more comfortable if it's supported by someone other than myself.

**Comment by atoomic** [comment]
sure no problems, I would need comaint permissions on pause and admin permissions on this github repo. If that works for you I can take care of it from there.
Thanks

**Comment by kohts** [comment]
> sure no problems, I would need comaint permissions on pause and admin permissions on this github repo. If that works for you I can take care of it from there.
> Thanks

pause: Added ATOOMIC to co-maintainers of Schedule::Cron::Events (Schedule-Cron-Events).
github: Collaborators: Push access to the repository: Awaiting atoomic’s response

**Comment by atoomic** [comment]
Thanks a lot Petya
I will play with it later

**Pull request merged**
